index:
  pattern: /
  defaults: { _controller: CASHMACHINEsimuladorCajeroBundle:Default:index }

retiroEfectivo:
  pattern: /retiroEfectivo
  defaults: { _controller: CASHMACHINEsimuladorCajeroBundle:Default:retiroEfectivo }

disposicionEfectivo:
  pattern: /disposicionEfectivo
  defaults: { _controller: CASHMACHINEsimuladorCajeroBundle:Default:disposicionEfectivo }
